// Ground Truth — measurement discipline case study. RUNNING per the author
// (2026-09-16); harness, statistics, publication pipeline and UI.
// Source: docs/portfolio/ground-truth.md

export const project = {
  slug: "ground-truth",
  name: "Ground Truth",
  tagline: "Eval & regression harness for document-field extraction accuracy",
  plain: "A test bench that says how accurate a document-reading model really is, with error bars anyone can recompute.",
  statement:
    "A benchmark is only useful when you can inspect how the number was produced.",
  status: {
    code: "running",
    label: "Running",
    detail:
      "Harness, statistics, publication pipeline and all six UI screens are built and running — 94 commits, 18 Sep 2025 → 9 Sep 2026. Status per the author, 2026-09-16; public repository to follow.",
  },
  category: ["AI & Evaluation", "Evidence"],
  role: "Sole engineer — design, statistics, implementation, publication",
  tech: ["Python 3.12", "Pydantic v2", "DuckDB", "NumPy / SciPy / scikit-learn", "Jinja2", "Next.js 16.3", "React 19.2", "TypeScript strict", "Playwright", "Docker Compose", "GitHub Actions"],
  flow: ["Corpus", "Grader", "Replicates (n ≥ 5)", "Statistics", "Calibration", "Leaderboard"],
  links: { github: "https://github.com/Berakhah/ground-truth" },
  licence: "Apache-2.0",

  card: {
    differentiator:
      "Every published figure is a bootstrap confidence interval, never a bare point estimate — and a stdlib-only script regenerates every leaderboard row from the published data alone, no repo checkout needed.",
    metrics: [
      {
        id: "gt-golden",
        value: "300",
        label: "synthetic golden items",
        context: "120 public (shipped, reproducible from a published seed) + 180 private, hash-committed.",
        evidence: {
          claim: "The golden set is 300 synthetic items: 120 public, 180 private.",
          method: "DETERMINISTIC",
          source: { label: "golden/ — seeded splits & manifests" },
          basis: "Two independent seeded generations, never one pool divided. The private split is committed as salted content hashes (sha256 with a 128-bit secret salt), proving the items existed at a date without revealing them.",
          observedAt: "2026-09",
          caveats: ["The golden set is synthetic — generated by the project’s own generator."],
        },
      },
      {
        id: "gt-tests",
        value: "408",
        label: "test functions",
        context: "~5,000 LOC of test code in 50 files; coverage floor 75% enforced by the compose smoke test.",
        evidence: {
          claim: "Ground Truth’s test suite contains 408 registered test functions.",
          method: "DETERMINISTIC",
          source: { label: "Repository — tests/ count" },
          basis: "Counted from the repository tree: 50 test files, ~5,000 lines of test code. Docker Compose ‘up’ runs the full suite with coverage as the smoke test.",
          observedAt: "2026-09",
          caveats: [],
        },
      },
      {
        id: "gt-nongoals",
        value: "6",
        label: "non-goals, AST-enforced",
        context: "No plugin system, no generic eval platform, no SaaS — violations are build failures.",
        evidence: {
          claim: "Six non-goals are enforced in CI by AST checks.",
          method: "DETERMINISTIC",
          source: { label: "tests/test_non_goals.py · docs/non-goals.md" },
          basis: "The test parses the codebase and fails the build on forbidden abstractions: no plugin system, no generic task abstraction, no multi-tenant SaaS, no bring-your-own-eval, no observability product, no prompt management.",
          observedAt: "2026-09",
          caveats: [],
        },
      },
      {
        id: "gt-terms",
        value: "17",
        label: "leaderboard terms, build-enforced",
        context: "assert_methodology_defines_every_term() fails the build on an undefined term.",
        evidence: {
          claim: "Every term the leaderboard uses is defined in the methodology — enforced, not promised.",
          method: "DETERMINISTIC",
          source: { label: "docs/methodology.md · tests/" },
          basis: "A test asserts that each of 17 leaderboard terms (accurate, correct, field, replicate, look, …) is defined in docs/methodology.md; an undefined term fails the build.",
          observedAt: "2026-09",
          caveats: [],
        },
      },
      {
        id: "gt-alpha",
        value: "α ≥ 0.667",
        label: "judge rejection threshold, pre-registered",
        context: "Below it, the field type is excluded from headline scoring and reported as not measured.",
        evidence: {
          claim: "LLM-judge agreement below α 0.667 excludes the field type from headline scoring.",
          method: "DETERMINISTIC",
          source: { label: "graders/judge/agreement.py" },
          basis: "Judge-vs-human agreement (Krippendorff’s α) is measured against a pre-registered rejection threshold. Bias controls are mandatory: randomised presentation order with an order-effect test, length-cue stripping, same-family judge rejected, n ≥ 3 majority vote.",
          observedAt: "2026-09",
          caveats: [],
        },
      },
    ],
    caveat:
      "The golden set is synthetic, so external validity is unmeasured by design and stated as such on the methodology page. Single-annotator ground truth is a known weakness; the design calls for blind 20% re-labelling and a second labeller.",
  },

  caseStudy: {
    problem:
      "Anyone choosing a model for a document-extraction task faces vendor benchmarks that are self-defined, unreproducible, and silent about sample size. “97% accuracy” with no n, no interval, no definition of “accurate,” and no held-out set is marketing, not measurement. The buyer’s real question — “do I need a frontier model for this, or will the cheap one do?” — is one no vendor is incentivised to answer.",
    whyFails: [
      "Vendor benchmarks are self-graded: the metric definition, the held-out set and the sample size are all chosen by the party being measured.",
      "Generic “eval platforms” fail structurally: the buyer must be technical enough to want APIs but not technical enough to run their own evals — and the category keeps getting absorbed into observability tooling.",
      "Point estimates without intervals invite over-reading: two models 0.4% apart on different days are usually indistinguishable, but a bare number hides that.",
    ],
    architecture: {
      intro:
        "Ground Truth deliberately does one task — field-extraction accuracy on pay-application and invoice documents — and refuses to generalise, enforcing that refusal in CI. It produces a public benchmark with a leaderboard where every figure is a bootstrap interval, calibration curves exported byte-stable for Ledger Sense’s confidence routing, and a paid triage deliverable that outputs automate / route-to-human / never-automate per intent with expected-value maths.",
      tree: `ground_truth/
  golden/       synthetic corpus generator, seeded public/private splits,
                manifests, rubric versioning
  graders/      deterministic/ (exact, numeric_tolerance, normalised, schema,
                arithmetic) · judge/ (majority vote + order/length effects;
                agreement: α + rejection)
  stats/        bootstrap (cluster-BCa interval), agreement (Cohen κ,
                Krippendorff α), correction (Benjamini–Hochberg),
                sequential (O'Brien-Fleming α-spending), mde
  matrix/       list-price cost model with cited source URL + retrieval date
  calibrate/    isotonic / Platt on replicate agreement; fit public,
                validate private; export
  regression/   fingerprint observation, drift detection gated on sequential
                boundary AND BH correction
  triage/       intake CSV → expected value → sensitivity sweep → flip point
                → print report
  publish/      leaderboard payload, methodology renderer, hash-keyed
                private verdicts
web/            leaderboard · items · judge · calibration · regression · triage`,
    },
    threatModel: [
      "**Self-serving measurement.** The tool itself could become a vendor — so the methodology opens by stating the population is synthetic and external validity is unmeasured by design.",
      "**Private-split leakage.** Published hashes must not let outsiders reconstruct private items: salted content hashes with a 128-bit secret salt mean a public generator plus a public seed enumerates nothing.",
      "**Judge manipulation.** LLM-as-judge is only used where a deterministic grader cannot reach, with pre-registered rejection thresholds and mandatory bias controls.",
      "**Data publication accidents.** A triage HTML was briefly published to Pages (caught 29 Aug 2026); the recorded incident now gates every publish step behind a mandatory security review.",
      "**Vendor relations.** Results are versioned and dated; corrections are new entries with the old value struck through; a right-of-reply process with 5/15-business-day windows and 10-day advance notice before naming a provider in a regression finding.",
    ],
    decisions: [
      {
        title: "Every rule has a test",
        body:
          "Private-split items never appear in published output; every number carries n, interval and method; temperature zero is not determinism (n ≥ 5 replicates, mean and variance reported); cost is published list price labelled as such, never measured spend. Each rule is enforced by a test, not a comment.",
      },
      {
        title: "Statistics code is the highest-risk directory",
        body:
          "Bootstrap CIs are validated against known distributions; Benjamini–Hochberg against the 1995 worked example; Cohen’s κ and Krippendorff’s α against published examples; O’Brien–Fleming boundaries validated under null simulation so 13 quarterly “looks” don’t inflate false positives.",
      },
      {
        title: "Two independent seeded generations, never one split pool",
        body:
          "The public and private splits are generated independently from separate seeds. The private hash is sha256(salt:seed:n:payload) with a 128-bit secret salt — a public generator plus a public seed gives an outsider no way to enumerate private items.",
      },
      {
        title: "Regression alerting as a statistics problem",
        body:
          "Drift is reported only when both the sequential boundary (O’Brien–Fleming α-spending) and the multiple-comparison correction (Benjamini–Hochberg) agree, with the test and p-value or interval stated — never a bare red arrow.",
      },
      {
        title: "The triage report shows the flip point",
        body:
          "A 92%-accurate intent with a $4 cost of error is automatable; a 97%-accurate one with a $40,000 cost of error is not. The report quotes the client’s own cost-of-error assumption and marks the recommendation that would flip under a plausible alternative as flipping.",
      },
      {
        title: "Admit when a version can’t be pinned",
        body:
          "On free tiers there is often no model fingerprint; the observation record says so rather than implying a version was tracked.",
      },
    ],
    implementation: [
      "Python 3.12, Pydantic v2, DuckDB (embedded, no server), NumPy/SciPy/scikit-learn, Jinja2. Next.js 16.3 / React 19.2 / TypeScript strict frontend with six screens: leaderboard, items, judge, calibration, regression, triage.",
      "~4,900 LOC of non-test Python across 122 files; ~1,700 LOC TypeScript with 34 Playwright specs.",
      "5 deterministic graders (exact, numeric tolerance, normalised, schema, arithmetic); LLM-as-judge only where deterministic graders cannot reach.",
      "scripts/reproduce.py — stdlib-only, no repo checkout needed — recomputes every leaderboard row from the published per-item verdicts and exits 0 on zero differences.",
      "Docker Compose ‘up’ runs the full test suite with coverage as the smoke test; weekly regression-watch cron; ruff, mypy --strict, gitleaks, no-float gate on the money path.",
      "Six accessible screens with a WCAG 2.2 AA gate, keyboard paths and print stylesheets; the latency free-tier caveat is exposed to assistive technology, not only on hover.",
    ],
    evidence: [
      "**A benchmark designed to be distrusted:** hash-committed private split, stdlib reproduction script, pre-registered analysis plan, right-of-reply process, corrections log.",
      "**A documented 46-defect self-audit** and a recorded data-leak incident (a triage HTML briefly published to Pages, caught 29 Aug 2026) that now gates every publish step behind a mandatory security review.",
      "**Byte-stable calibration exports** — isotonic/Platt curves per field type, fit on public data and validated on private, exported for Ledger Sense’s confidence routing.",
      "**Reproducibility test:** published numbers regenerate from published data alone; the private split never appears in published output.",
    ],
    securityControls: [
      "**Private-split discipline:** only salted content hashes of private items are published, proving existence at a date without revealing content.",
      "**Publish-gate security review:** every publish step is gated behind a mandatory security review since the recorded 29 Aug 2026 incident.",
      "**No vendor characterisation:** results are versioned and dated; corrections are new entries with struck-through old values; right-of-reply with defined windows.",
      "**Cost transparency:** cost is published list price with cited source URL and retrieval date per slot — labelled as list price, never presented as measured spend.",
    ],
    tradeoffs: [
      "**One task, refusing to generalise** — enforced by AST-checked non-goals. Costs market breadth; buys methodological integrity.",
      "**Synthetic corpus** — fully reproducible and license-clean, at the price of unmeasured external validity until a real-invoice corpus exists.",
      "**Bootstrap intervals everywhere** make every number heavier to compute and read — and honest in a way point estimates are not.",
    ],
    limitations: [
      "The golden set is synthetic — there is no real-invoice corpus to validate against.",
      "Single-annotator ground truth is a known weakness; the design calls for blind 20% re-labelling and a second labeller.",
      "The provider audit (terms, training-on-input, list prices with dated sources) is re-run whenever a provider changes its catalogue.",
      "External validity is unmeasured by design and stated as such on the methodology page.",
    ],
    currentStatus:
      "Running — harness, statistics, publication pipeline and all six UI screens; 94 commits between 18 Sep 2025 and 9 Sep 2026. Status per the author, 2026-09-16; public repository to follow. Licence: Apache-2.0.",
    repoNote:
      "Public repository: github.com/Berakhah/ground-truth.",
  },
};
